# Generated by Django 3.1.2 on 2021-01-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaForm', '0002_auto_20210113_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencesearch',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
