# Generated by Django 3.1.2 on 2021-01-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaForm', '0003_sequencesearch_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencesearch',
            name='still_running',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
